version: '3.9'

services:
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__Secret=super-secret-key
      - JwtSettings__ExpiryMinutes=60
      - JwtSettings__Issuer=myself
      - Audience__Issuer=myself
    ports:
      - "5110:80"
