POST {{host}}/{{auth_path}}/register
Content-Type: application/json

{
    "firstName": "Giovanni",
    "lastName": "demo",
    "username": "giovanni@test.demo",
    "password": "S0meValidpa$$wd"
}

### validation error

POST {{host}}/{{auth_path}}/register
Content-Type: application/json

{
    "firstName": "",
    "lastName": "demo",
    "username": "",
    "password": "somepwd"
}
