POST {{host}}/{{auth_path}}/login
Content-Type: application/json

{
    "username": "giovanni@test.demo",
    "password": "S0meValidpa$$wd"
}

### error invalid username

POST {{host}}/{{auth_path}}/login
Content-Type: application/json

{
    "username": "giovanni@test.dem",
    "password": "somepwd"
}

### error invalid creds

POST {{host}}/{{auth_path}}/login
Content-Type: application/json

{
    "username": "giovanni@test.demo",
    "password": "wrongpwd"
}

### error data validation

POST {{host}}/{{auth_path}}/login
Content-Type: application/json

{
    "username": "",
    "password": ""
}