Get {{host}}/{{identity_path}}/get/giovanni@test.demo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTg2ZGZjNS03ZjE0LTQ5ZWMtYmQ2MC1mNWI3YTZhNGZlOTEiLCJnaXZlbl9uYW1lIjoiR2lvdmFubmkiLCJmYW1pbHlfbmFtZSI6ImRlbW8iLCJqdGkiOiI4MWZjZTAyNi02NzI3LTRmYmQtYTVmOC1kZmFkM2JhZjcwZTEiLCJleHAiOjE2NjEyNzg4NzQsImlzcyI6Im15c2VsZiIsImF1ZCI6Im15c2VsZiJ9.00W91ZlFwJajEtn7ubedwu4GLn_sgqiq2uU3_ehhHKw