trigger: none

variables:
  major: 1
  minor: 1
  patch: $[counter(variables['minor'], 1)]
  version: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]
  solution: 'ErrorFlow.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: $(version).$(build.buildId)

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\IdentityApi.$(build.buildNumber).zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  enabled: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'