name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/cryptic-wizard/run-specflow-tests@v1.3.1
      with:
        test-assembly-path: tests/Identity.Api.Tests.Acceptance/bin/Release/net6.0
        test-assembly-dll: Identity.Api.Tests.Acceptance.dll
        output-html: LivingDoc.html
